path_to_host_ref_file: /home/giulia/Workspace/PhytoPhD/caliag/GDDH13_1-1_formatted.fasta
path_to_target_genome_file: /home/giulia/Workspace/PhytoPhD/caliag/ref/NC_011047.1_capm_AT.fasta
path_to_reads_file: /home/giulia/Workspace/PhytoPhD/caliag/PMs/Cmel17_AT2/Nanopore/Cmel17_nonHost.fastq
name: prova_pmbz
filt_python_script: /home/giulia/Workspace/PhytoPhD/scripts/fasta_filter_mod_mic.py
contig_sel_python_script: ""
path_to_r1_file: ""
path_to_r2_file: ""
minimap2_samtools_simg: /home/giulia/Workspace/PhytoPhD/VM_try_singularity/minim2_samtools.simg
samtools_simg:  /home/giulia/Workspace/PhytoPhD/VM_try_singularity/samtools.simg
biopython_simg: /home/giulia/Workspace/PhytoPhD/VM_try_singularity/biopy_pysam_pandas.simg
flye_simg: /home/giulia/Workspace/PhytoPhD/VM_try_singularity/flye.simg
medaka_simg: /home/giulia/Workspace/PhytoPhD/VM_try_singularity/medaka_dm_mic.simg
blastn_simg: /home/giulia/Workspace/PhytoPhD/VM_try_singularity/blastn.simg
byopy_pysam_pandas_simg: /home/giulia/Workspace/PhytoPhD/VM_try_singularity/biopy_pysam_pandas.simg
pilon_simg: ""
