path_to_host_ref_file: /home/GDDH13_1-1_formatted.fasta
path_to_target_genome_file: /home/ref/NC_011047.1_capm_AT.fasta
path_to_reads_file: /home/Cmel17_AT2/Nanopore/Cmel17_nonHost.fastq
name: prova_pmbz
filt_python_script: /home/scripts/fasta_filter_mod_mic.py
contig_sel_python_script: ""
path_to_r1_file: ""
path_to_r2_file: ""
minimap2_samtools_simg: /home/minim2_samtools.simg
samtools_simg:  /home/samtools.simg
biopython_simg: /home/biopy_pysam_pandas.simg
flye_simg: /home/flye.simg
medaka_simg: /home/medaka_dm_mic.simg
blastn_simg: /home/blastn.simg
byopy_pysam_pandas_simg: /home/biopy_pysam_pandas.simg
pilon_simg: ""
